# Generated by Django 4.2.4 on 2023-08-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_alter_team_created_by"),
        ("client", "0002_alter_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
