# Generated by Django 4.2.4 on 2023-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="email_idx"),
        ),
    ]
