# Generated by Django 4.2.4 on 2023-08-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_alter_client_created_at_client_email_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mailing address"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="social",
            field=models.TextField(
                blank=True, null=True, verbose_name="Social media link"
            ),
        ),
    ]
