# Generated by Django 4.2.4 on 2023-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_client_address_client_phone_client_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="social",
            field=models.URLField(
                blank=True, null=True, verbose_name="Social media link"
            ),
        ),
    ]
