# Generated by Django 4.2.4 on 2023-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_alter_client_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
