# Generated by Django 4.2.4 on 2023-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="preferred_communication",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("mail", "Mail"),
                    ("phone", "Phone"),
                    ("social_media", "Social"),
                ],
                default="mail",
                max_length=15,
            ),
        ),
    ]
