# Generated by Django 4.2.4 on 2023-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userentity",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Required. Enter a valid email address",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
