# Generated by Django 4.2.4 on 2023-08-04 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("sales", "Sales"),
                    ("agent", "Agent"),
                    ("marketing", "Marketing"),
                ],
                default="sales",
                max_length=12,
            ),
        ),
    ]
