# Generated by Django 4.2.4 on 2023-08-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_team_department_alter_team_name_team_name_idx"),
        ("userprofile", "0002_userprofile_date_joined_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="team",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="team.team",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("sales", "Sales"),
                    ("lead", "Lead"),
                    ("marketing", "Marketing"),
                ],
                default="sales",
                max_length=12,
            ),
        ),
    ]
