# Generated by Django 4.2.4 on 2023-08-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_alter_team_created_by"),
        ("lead", "0002_lead_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="teams",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
