# Generated by Django 4.2.4 on 2023-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_lead_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mailing address"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="social",
            field=models.TextField(
                blank=True, null=True, verbose_name="Social media link"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["priority"], name="priority_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["is_client"], name="is_client_idx"),
        ),
    ]
