# Generated by Django 4.2.4 on 2023-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0004_lead_address_lead_phone_lead_social_lead_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="social",
            field=models.URLField(
                blank=True, null=True, verbose_name="Social media link"
            ),
        ),
    ]
