# Generated by Django 4.2.4 on 2023-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0006_lead_preferred_communication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
